#!/usr/bin/env python3
"""Extract the AMBE+2 quantiser tables from the DM-32UV firmware image.

    tools/extract_tables.py ../firmware/DM32_L01_048_20250821.bin > src/ambe_tables_fw.c

HOW THE TABLES WERE LOCATED
---------------------------
The vocoder's constant pool is not addressed in flash: it lives in the
SRAM_SAHB window at 0x18000000, which the image populates at startup.  The
mapping was fixed by two independent anchors that agree exactly:

  * the 512-entry cosine table the harmonic synthesiser indexes (g_awSineTable512,
    SRAM 0x18001630) is at file 0x064CF0, and
  * Vocoder_CodeSpectralCoefficients 0x000220D4 loads its codebook pointers from
    the literal pool at 0x00022480, which reads 0x18002090 for the first codebook;
    that codebook is at file 0x065750.

Both give   SRAM 0x18000000  <->  file 0x000636C0   (VA 0x0306F5C0).

Every pointer in that literal pool then lands exactly on a table boundary:

    0x18002030 -> 0x0656F0   block lengths, 48 x uint16, nibble packed
    0x18002090 -> 0x065750   PRBA24  512 x 3
    0x18002C90 -> 0x066350   PRBA58  128 x 4
    0x18003090 -> 0x066750   HOC b5   32 x 4
    0x18003190 -> 0x066850   HOC b6   16 x 4
    0x18003210 -> 0x0668D0   HOC b7   16 x 4
    0x18003290 -> 0x066950   HOC b8    8 x 4
    0x180038B4 -> 0x066F74   gain quantiser, 32 entries
                             (from Vocoder_LookupAndBlendGain 0x0002AE70's pool
                              at 0x0002AFA8)

The six codebooks are perfectly contiguous, 0x065750..0x066990, 4672 bytes.
The bit widths Vocoder_CodeSpectralCoefficients passes for them - 9, 7, 5, 4, 4,
3 - are exactly the widths of b3..b8, which is what confirms the identification
rather than the numerical match alone.

FORMAT
------
All value tables are signed 16-bit, Q11 (scale 2048).  Fitting each against
mbelib's floats by least squares recovers a scale of 2048.00 and a worst-case
residual of half an LSB, i.e. the firmware's values and mbelib's reconstruction
agree to the firmware's own precision.

The block-length table is one uint16 per L (L = 9..56), holding four 4-bit
fields, least significant first, each biased by +2:

    Ji[i] = ((word >> (4*i)) & 0xF) + 2

which is why a byte-level search for it never found anything.  It reproduces
mbelib's AmbeLmprbl for all 48 rows.
"""
import sys

BASE = 0x0636C0           # file offset that SRAM 0x18000000 is loaded from
Q11 = 2048

TABLES = [
    # name              sram        count  cols
    ("ambe_prba24_q11", 0x18002090, 512,   3),
    ("ambe_prba58_q11", 0x18002c90, 128,   4),
    ("ambe_hoc_b5_q11", 0x18003090, 32,    4),
    ("ambe_hoc_b6_q11", 0x18003190, 16,    4),
    ("ambe_hoc_b7_q11", 0x18003210, 16,    4),
    ("ambe_hoc_b8_q11", 0x18003290, 8,     4),
    ("ambe_dg_q11",     0x180038b4, 32,    1),
]
LMPRBL_SRAM = 0x18002030
LMPRBL_N = 48             # L = 9..56
VUV_SRAM = 0x18003628     # 128 x uint32, 2 bits per voicing band
VUV_N = 128


def s16(raw, off):
    v = raw[off] | (raw[off + 1] << 8)
    return v - 65536 if v >= 32768 else v


def emit(name, vals, per_line, comment):
    print("/* %s */" % comment)
    print("const short %s[%d] = {" % (name, len(vals)))
    for i in range(0, len(vals), per_line):
        row = ", ".join("%6d" % v for v in vals[i:i + per_line])
        print("    " + row + ("," if i + per_line < len(vals) else ""))
    print("};")
    print()


def main():
    raw = open(sys.argv[1], "rb").read()
    print("""
/*
 * ambe_tables_fw.c - AMBE+2 quantiser tables read out of the DM-32UV firmware.
 *
 * GENERATED by tools/extract_tables.py from
 *   firmware/DM32_L01_048_20250821.bin
 *   sha256 fda860febfcf1a234eed7fa73272112891074aac83746e4f8dfe224a2a700f8f
 * Do not edit by hand.  See that script for how each table was located and for
 * the firmware addresses; every table below is a verbatim copy of bytes in the
 * image, not a transcription of anyone else's values.
 *
 * All value tables are signed 16-bit Q11: divide by 2048 for the real value.
 *
 * SPDX-License-Identifier: ISC
 */
#include "ambe_tables.h"
""".strip())
    print()

    for name, sram, count, cols in TABLES:
        off = sram - 0x18000000 + BASE
        n = count * cols
        vals = [s16(raw, off + 2 * i) for i in range(n)]
        emit(name, vals, cols if cols > 1 else 8,
             "SRAM 0x%08X, file 0x%06X, %d x %d, Q11" % (sram, off, count, cols))

    # block lengths: unpack the nibbles into a plain [57][4], L = 0..56
    off = LMPRBL_SRAM - 0x18000000 + BASE
    ji = [0] * (57 * 4)
    for k in range(LMPRBL_N):
        w = raw[off + 2 * k] | (raw[off + 2 * k + 1] << 8)
        L = 9 + k
        for i in range(4):
            ji[L * 4 + i] = ((w >> (4 * i)) & 0xF) + 2
    # voicing patterns, exactly as the firmware stores and indexes them
    off = VUV_SRAM - 0x18000000 + BASE
    vuv = []
    for k in range(VUV_N):
        w = (raw[off + 4*k] | (raw[off + 4*k + 1] << 8) |
             (raw[off + 4*k + 2] << 16) | (raw[off + 4*k + 3] << 24))
        vuv.append(w)
    print("/* SRAM 0x%08X, file 0x%06X, %d x uint32.  Two bits per voicing band,"
          % (VUV_SRAM, off, VUV_N))
    print(" * most significant crumb first; the low bit of each crumb is the band's")
    print(" * voiced flag.  Vocoder_DecodeSpectralCodebookEntry 0x00022DB4 indexes this")
    print(" * with the b1 field left-justified to 7 bits, so for the 2450 mode's 5-bit")
    print(" * b1 the index is b1 << 2.  Crumb values 0, 1 and 2 all occur; only bit 0")
    print(" * is used here. */")
    print("const unsigned int ambe_vuv_packed[%d] = {" % VUV_N)
    for i in range(0, VUV_N, 4):
        row = ", ".join("0x%08Xu" % v for v in vuv[i:i+4])
        print("    " + row + ("," if i + 4 < VUV_N else ""))
    print("};")
    print()

    emit("ambe_lmprbl", ji, 4,
         "SRAM 0x%08X, file 0x%06X, 48 x uint16 nibble-packed, unpacked to [57][4];"
         " rows 0..8 are unused (L >= 9)" % (LMPRBL_SRAM, off))


if __name__ == "__main__":
    main()
