#!/usr/bin/env python3
"""Generate src/ambe_tables_unresolved.c from an mbelib checkout.

These are the AMBE+2 tables that have NOT been located in the DM-32UV image.
Everything else the decoder uses now comes from the firmware itself - see
tools/extract_tables.py.

What was searched for, and how, before giving up on each:

  ambe_w0_table   the 120-entry pitch quantiser.  Scanned the whole 860 KiB as
                  int16 and int32, against f0, w0 = 2*pi*f0, 1/f0 and log2(f0),
                  with a per-offset least-squares scale fit and a half-LSB
                  residual test - the same test that found every codebook.  No
                  candidate.  A pure log-linear law does not fit it either: the
                  best fit, f0 = 2^(-(b0 + 196.109)/45.372), leaves a structured
                  residual up to 3e-3 in log2 and gets L wrong for 2 of 120
                  indices, so the firmware is not simply evaluating the patent
                  formula.

  ambe_l_table    120 harmonic counts.  Not independent: floor(0.4627 / f0)
                  reproduces all 120 entries exactly, so only the pitch table
                  above is really unresolved.  Kept here because it derives from
                  a table that is.

The voicing table and the synthesis window used to be listed here and are not
any more: the voicing patterns were found at SRAM 0x18003628 (a packing no byte
search could have matched - see tools/extract_tables.py), and the window turned
out not to be a firmware object at all, so ambe_synth.c generates it from its
three-slope definition instead.

The lead for the pitch table is the function that consumes b0.  Reading its
literal pool is how every other table here was found; the b0 field is read six
bits at a time by the frame decoder at 0x0002033C, whose per-mode descriptor
argument carries the field widths, so that descriptor is the thing to chase.

Usage: gen_unresolved_tables.py <mbelib-checkout> > ../src/ambe_tables_unresolved.c
"""
import re
import sys


def grab(src, decl):
    i = src.index(decl)
    j = src.index("{", i)
    k = src.index("};", j)
    return [float(x) for x in re.findall(r"-?\d+\.?\d*(?:[eE][-+]?\d+)?", src[j:k])]


def cfloat(v):
    s = "%.9g" % v
    if "." not in s and "e" not in s and "E" not in s:
        s += ".0"
    return s + "f"


def emit_f(name, vals, per_line=6):
    print("const float %s[%d] = {" % (name, len(vals)))
    for i in range(0, len(vals), per_line):
        row = ", ".join(cfloat(v) for v in vals[i:i + per_line])
        print("    " + row + ("," if i + per_line < len(vals) else ""))
    print("};")
    print()


def emit_i(name, vals, per_line=12):
    print("const short %s[%d] = {" % (name, len(vals)))
    for i in range(0, len(vals), per_line):
        row = ", ".join("%d" % int(v) for v in vals[i:i + per_line])
        print("    " + row + ("," if i + per_line < len(vals) else ""))
    print("};")
    print()


def main():
    root = sys.argv[1]
    amb = open(root + "/ambe3600x2450_const.h").read()
    com = open(root + "/mbelib_const.h").read()

    print("""/*
 * ambe_tables_unresolved.c - the AMBE+2 tables still sourced from mbelib.
 *
 * GENERATED by tools/gen_unresolved_tables.py -- do not edit by hand.
 *
 * Everything else the decoder uses is extracted from the radio image by
 * tools/extract_tables.py.  These four have not been located in it yet; that
 * script's docstring records exactly what was searched for and where the
 * remaining leads are.  Until they are found, this file is the one place the
 * decoder is not built from the firmware.
 *
 * Source: mbelib (https://github.com/szechyjs/mbelib), ISC licensed,
 * Copyright (C) 2010 mbelib Author.
 *
 * SPDX-License-Identifier: ISC
 */
#include "ambe_tables.h"
""")
    emit_f("ambe_w0_table", grab(amb, "AmbeW0table[120]"))
    emit_i("ambe_l_table", grab(amb, "AmbeLtable[120]"))


if __name__ == "__main__":
    main()
