/*
 * ambe_tables_unresolved.c - the AMBE+2 tables still sourced from mbelib.
 *
 * GENERATED by tools/gen_unresolved_tables.py -- do not edit by hand.
 *
 * Everything else the decoder uses is extracted from the radio image by
 * tools/extract_tables.py.  These four have not been located in it yet; that
 * script's docstring records exactly what was searched for and where the
 * remaining leads are.  Until they are found, this file is the one place the
 * decoder is not built from the firmware.
 *
 * Source: mbelib (https://github.com/szechyjs/mbelib), ISC licensed,
 * Copyright (C) 2010 mbelib Author.
 *
 * SPDX-License-Identifier: ISC
 */
#include "ambe_tables.h"

const float ambe_w0_table[120] = {
    0.049971f, 0.049215f, 0.048471f, 0.047739f, 0.04701f, 0.046299f,
    0.045601f, 0.044905f, 0.044226f, 0.043558f, 0.0429f, 0.042246f,
    0.041609f, 0.040979f, 0.040356f, 0.039747f, 0.039148f, 0.038559f,
    0.037971f, 0.037399f, 0.036839f, 0.036278f, 0.035732f, 0.035198f,
    0.034672f, 0.034145f, 0.033636f, 0.033133f, 0.032635f, 0.032148f,
    0.03167f, 0.031122f, 0.030647f, 0.030184f, 0.029728f, 0.029272f,
    0.028831f, 0.028395f, 0.027966f, 0.027538f, 0.027122f, 0.026712f,
    0.026304f, 0.025906f, 0.025515f, 0.025129f, 0.024746f, 0.024372f,
    0.024002f, 0.023636f, 0.023279f, 0.022926f, 0.022581f, 0.022236f,
    0.0219f, 0.02157f, 0.02124f, 0.02092f, 0.020605f, 0.020294f,
    0.019983f, 0.019684f, 0.019386f, 0.019094f, 0.018805f, 0.01852f,
    0.018242f, 0.017965f, 0.017696f, 0.017431f, 0.01717f, 0.016911f,
    0.016657f, 0.016409f, 0.016163f, 0.015923f, 0.015686f, 0.015411f,
    0.015177f, 0.014946f, 0.014721f, 0.014496f, 0.014277f, 0.014061f,
    0.013847f, 0.013636f, 0.01343f, 0.013227f, 0.013025f, 0.012829f,
    0.012634f, 0.012444f, 0.012253f, 0.012068f, 0.011887f, 0.011703f,
    0.011528f, 0.011353f, 0.011183f, 0.011011f, 0.010845f, 0.010681f,
    0.010517f, 0.010359f, 0.010202f, 0.01005f, 0.009895f, 0.009747f,
    0.0096f, 0.009453f, 0.009312f, 0.009172f, 0.009033f, 0.008896f,
    0.008762f, 0.008633f, 0.008501f, 0.008375f, 0.008249f, 0.008125f
};

const short ambe_l_table[120] = {
    9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10,
    11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 13,
    13, 13, 13, 13, 14, 14, 14, 14, 15, 15, 15, 15,
    16, 16, 16, 16, 17, 17, 17, 17, 18, 18, 18, 18,
    19, 19, 19, 20, 20, 20, 21, 21, 21, 22, 22, 22,
    23, 23, 23, 24, 24, 24, 25, 25, 26, 26, 26, 27,
    27, 28, 28, 29, 29, 30, 30, 30, 31, 31, 32, 32,
    33, 33, 34, 34, 35, 36, 36, 37, 37, 38, 38, 39,
    40, 40, 41, 42, 42, 43, 43, 44, 45, 46, 46, 47,
    48, 48, 49, 50, 51, 52, 52, 53, 54, 55, 56, 56
};

